// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrrCeBtyWdysFbvD7EN6KF7j2GrZ25TyU',
    appId: '1:808624128150:android:313cdc0d248b32bac842b7',
    messagingSenderId: '808624128150',
    projectId: 'konecta-de502',
    storageBucket: 'konecta-de502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXBk1y68kWDzuFp3gImMqUumNHiaIRWYU',
    appId: '1:808624128150:ios:0d9c3e7a41a51807c842b7',
    messagingSenderId: '808624128150',
    projectId: 'konecta-de502',
    storageBucket: 'konecta-de502.firebasestorage.app',
    androidClientId: '808624128150-gh89ra1t49vi8nhviot84usepghgia07.apps.googleusercontent.com',
    iosClientId: '808624128150-ckmtlutcv0ghtre9nbebii5dk8evsho7.apps.googleusercontent.com',
    iosBundleId: 'com.example.konecta',
  );
}
